# Generated by Django 4.1.7 on 2023-03-11 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_rename_menu_point'),
    ]

    operations = [
        migrations.RenameField(
            model_name='point',
            old_name='category',
            new_name='Parent',
        ),
    ]
