# Generated by Django 4.1.7 on 2023-03-11 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_rename_point_branch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='Parent',
            new_name='parent',
        ),
    ]
