# Generated by Django 4.1.7 on 2023-03-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_alter_branch_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='url',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
