# Generated by Django 4.1.7 on 2023-03-24 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0014_remove_branch_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
