# Generated by Django 4.1.7 on 2023-03-24 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0015_branch_url_alter_branch_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='url',
        ),
    ]
